name: Auto Release on TOC Update

on:
  push:
    branches:
      - main
    paths:
      - '**/*.toc'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 1. Читаем версию из файла
      - name: Get version from .toc
        id: read_version
        run: |
          TOC_FILE=$(find . -maxdepth 2 -name "*.toc" | head -n 1)
          if [ -z "$TOC_FILE" ]; then
            echo "Ошибка: .toc файл не найден!"
            exit 1
          fi
          VERSION=$(grep -i "## Version:" "$TOC_FILE" | awk -F ':' '{print $2}' | tr -d ' \r\n')
          if [ -z "$VERSION" ]; then
            echo "Ошибка: Строка '## Version:' пустая!"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Archive
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          TAG_NAME="${{ steps.read_version.outputs.version }}"
          
          git archive --format=zip HEAD --prefix="${REPO_NAME}/" -o "${REPO_NAME}-${TAG_NAME}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.read_version.outputs.version }}
          name: v${{ steps.read_version.outputs.version }}
          files: ${{ github.event.repository.name }}-${{ steps.read_version.outputs.version }}.zip
          draft: false
          prerelease: false
